title: Homelab Documentation
description: Documentation for my homelab setup and configurations
theme: just-the-docs

url: https://homelab.blue

# Logo
logo: "/assets/images/logo.png"

# Set a path/url to a favicon
favicon_ico: "/assets/images/favicon.ico"

# Enable or disable the site search
search_enabled: true

# Set the search token separator
search_tokenizer_separator: /[\s/]+/

# Enable or disable heading anchors
heading_anchors: true

# Color scheme
color_scheme: light

# External navigation links
nav_external_links:
  - title: Homelab GitHub Repository
    url: https://github.com/homelab-bg/homelab
    hide_icon: false

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer content
footer_content: "Copyright &copy; 2024. Distributed under the <a href=\"https://github.com/homelab-bg/homelab-docs/blob/main/LICENSE\">MIT license.</a>"

# Footer "Edit this page on GitHub" link text
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/homelab-bg/homelab-docs"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"

# Aux links for the upper right navigation
aux_links:
  "Homelab Blue":
    - "https://homelab.blue"

# Makes Aux links open in a new tab
aux_links_new_tab: false

# Enable copy code button
enable_copy_code_button: true